spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: "postgres"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

app:
  title: Lampwork
  subtitle: Marketplace
  email: shvetson@gmail.com
  phone: +7(916) 610-90-92
  copyright: Oleg Shvets
  copyrightFrom: 2022

upload:
  path: /home/master/Downloads/files


